### ISSUE TITLE
"Image View" is not full screen

### ISSUE THREAD

**Issue by agguser** [wjaguar/mtPaint#47] opened 2021-02-03 05:06 UTC
If (on Linux) you take a screenshot with `mtpaint -s -v` (or `mtpaint -s`, maximize it, then press key <kbd>Home</kbd>  (menu View> Toggle Image View)), youʼll notice that there are a little bar at the top and scrollbars at the right and the bottom.

How to display an image fullscreen, showing scrollbars only when needed?

**Comment by wjaguar** [comment] 2021-02-03 14:33
A maximized window is still a window, thus by definition smaller than a screenshot of an entire screen, thus requiring scrollbars when displaying it. As to true fullscreening, mtPaint does not do that at present.
Never saw a reason to fullscreen a still-image viewer, much less an image editor. But can add it as an option if there is a need for it.

**Comment by agguser** [comment] 2021-02-03 15:39
I use a window manager with disable window's title bar and borders, so I wonder why, even maximized, image view mode shows scrollbars and a small bar (not a title bar) on top.

(I use this when comparing current screen with captured screen (screenshot) after changing color theme)

**Comment by wjaguar** [comment] 2021-02-03 21:10
Thanks for noticing and taking the time to report this thing.
The problem is GTK+3 specific; seems GtkFlowBox still wants some space even when having no visible children. Will look into doing something to it for that. :)

As to comparing, isn't it easier to take another screenshot (through Image->New) and then swap the two images back and forth using Undo & Redo? mtPaint does have that "Undoable" checkbox there for a reason. ;)

**Comment by agguser** [comment] 2021-02-04 03:28
You meant File>New? Well, that's an alternative, but take more time. Thanks for looking into it.

**Comment by wjaguar** [comment] 2021-02-06 22:15
Fixed in 3.50.05 in init_css()

**Closed** 2021-02-06 22:15 UTC
